services:
    backend:
        build:
            context: ./backend
        container_name: sudoku-backend
        restart: unless-stopped
        ports:
            - "8081:9000"
            - "8082:8082"
        volumes:
            - ./backend:/usr/src/app
        working_dir: /usr/src/app
        entrypoint: /usr/src/app/RUN.sh #tail -F /dev/null 
    frontend:
        build:
            context: ./frontend
        container_name: sudoku-frontend
        restart: unless-stopped
        ports:
            - "8080:4200"
        volumes:
            - ./frontend:/usr/src/app
        working_dir: /usr/src/app
        entrypoint: /usr/src/app/RUN.sh #tail -F /dev/null
        depends_on:
            - backend